/* DEV GYM exercise library v2 — expanded bilingual training database. */
window.DEV_EXERCISES = [
{id:'incline-db-press',cat:'chest',sub:'upper',en:'Incline Dumbbell Press',ar:'ضغط دمبل مائل للأعلى',eq:'dumbbell',sets:4,reps:'8–10',rest:'90–120s',rir:'1–2'},
{id:'incline-bb-press',cat:'chest',sub:'upper',en:'Incline Barbell Press',ar:'ضغط بار مائل للأعلى',eq:'barbell',sets:4,reps:'6–10',rest:'120s',rir:'1–2'},
{id:'incline-smith-press',cat:'chest',sub:'upper',en:'Incline Smith Machine Press',ar:'ضغط صدر علوي سميث',eq:'machine',sets:3,reps:'8–12',rest:'90s',rir:'1–2'},
{id:'incline-plate-press',cat:'chest',sub:'upper',en:'Incline Plate-Loaded Chest Press',ar:'ضغط صدر علوي جهاز أوزان حرة',eq:'machine',sets:3,reps:'8–12',rest:'90s',rir:'1–2'},
{id:'incline-cable-fly',cat:'chest',sub:'upper',en:'Incline Cable Fly',ar:'تفتيح كيبل صدر علوي',eq:'cable',sets:3,reps:'10–15',rest:'60–75s',rir:'1–2'},
{id:'plate-loaded-chest-press',cat:'chest',sub:'mid',en:'Plate-Loaded Chest Press',ar:'ضغط صدر جهاز أوزان حرة',eq:'machine',sets:3,reps:'8–12',rest:'90s',rir:'1–2'},
{id:'push-up',cat:'chest',sub:'mid',en:'Push-Up',ar:'تمرين الضغط',eq:'bodyweight',sets:3,reps:'8–20',rest:'60–90s',rir:'1–2'},
{id:'wide-push-up',cat:'chest',sub:'mid',en:'Wide-Grip Push-Up',ar:'تمرين ضغط قبضة واسعة',eq:'bodyweight',sets:3,reps:'8–20',rest:'60–90s',rir:'1–2'},
{id:'seated-cable-chest-press',cat:'chest',sub:'mid',en:'Seated Cable Chest Press',ar:'ضغط صدر كيبل جالس',eq:'cable',sets:3,reps:'10–15',rest:'60–75s',rir:'1–2'},
{id:'dumbbell-pullover',cat:'chest',sub:'mid',en:'Dumbbell Pullover',ar:'دمبل بول أوفر',eq:'dumbbell',sets:3,reps:'10–15',rest:'75s',rir:'1–2'},
{id:'incline-db-fly',cat:'chest',sub:'upper',en:'Incline Dumbbell Fly',ar:'تفتيح دمبل صدر علوي',eq:'dumbbell',sets:3,reps:'10–15',rest:'75s',rir:'1–2'},
{id:'low-high-cable-fly',cat:'chest',sub:'upper',en:'Low to High Cable Fly',ar:'تفتيح كيبل من أسفل لأعلى',eq:'cable',sets:3,reps:'10–15',rest:'60–75s',rir:'1–2'},
{id:'flat-db-press',cat:'chest',sub:'mid',en:'Dumbbell Bench Press',ar:'ضغط دمبل مستوي',eq:'dumbbell',sets:3,reps:'8–12',rest:'90s',rir:'1–2'},
{id:'flat-bb-press',cat:'chest',sub:'mid',en:'Barbell Bench Press',ar:'ضغط بار مستوي',eq:'barbell',sets:4,reps:'6–10',rest:'120s',rir:'1–2'},
{id:'flat-smith-press',cat:'chest',sub:'mid',en:'Flat Smith Machine Press',ar:'ضغط صدر مستوي سميث',eq:'machine',sets:3,reps:'8–12',rest:'90s',rir:'1–2'},
{id:'chest-press-machine',cat:'chest',sub:'mid',en:'Chest Press Machine',ar:'ضغط صدر جهاز',eq:'machine',sets:3,reps:'8–12',rest:'90s',rir:'1–2'},
{id:'db-chest-fly',cat:'chest',sub:'mid',en:'Dumbbell Chest Fly',ar:'تفتيح صدر دمبل',eq:'dumbbell',sets:3,reps:'10–15',rest:'75s',rir:'1–2'},
{id:'pec-deck-fly',cat:'chest',sub:'mid',en:'Pec Deck Fly',ar:'تفتيح صدر بيك ديك',eq:'machine',sets:3,reps:'10–15',rest:'60–75s',rir:'1–2'},
{id:'flat-cable-fly-bench',cat:'chest',sub:'mid',en:'Flat Cable Fly on Bench',ar:'تفتيح كيبل على بنش مستوي',eq:'cable',sets:3,reps:'10–15',rest:'60–75s',rir:'1–2'},
{id:'mid-cable-fly',cat:'chest',sub:'mid',en:'Mid Cable Fly',ar:'تفتيح كيبل متوسط',eq:'cable',sets:3,reps:'10–15',rest:'60–75s',rir:'1–2'},
{id:'decline-db-press',cat:'chest',sub:'lower',en:'Decline Dumbbell Press',ar:'ضغط دمبل صدر سفلي',eq:'dumbbell',sets:3,reps:'8–12',rest:'90s',rir:'1–2'},
{id:'decline-bb-press',cat:'chest',sub:'lower',en:'Decline Barbell Press',ar:'ضغط بار صدر سفلي',eq:'barbell',sets:3,reps:'6–10',rest:'120s',rir:'1–2'},
{id:'decline-smith-press',cat:'chest',sub:'lower',en:'Decline Smith Machine Press',ar:'ضغط صدر سفلي سميث',eq:'machine',sets:3,reps:'8–12',rest:'90s',rir:'1–2'},
{id:'high-to-low-fly',cat:'chest',sub:'lower',en:'High to Low Cable Fly',ar:'تفتيح كيبل من أعلى لأسفل',eq:'cable',sets:3,reps:'10–15',rest:'60–90s',rir:'1–2'},
{id:'chest-dips',cat:'chest',sub:'lower',en:'Chest Dips',ar:'متوازي للصدر',eq:'bodyweight',sets:3,reps:'6–15',rest:'90s',rir:'1–2'},

{id:'lat-pulldown',cat:'back',sub:'lats',en:'Lat Pulldown',ar:'سحب أمامي للاتس',eq:'cable',sets:4,reps:'8–12',rest:'90s',rir:'1–2'},
{id:'neutral-pulldown',cat:'back',sub:'lats',en:'Neutral-Grip Lat Pulldown',ar:'سحب لاتس قبضة محايدة',eq:'cable',sets:3,reps:'8–12',rest:'90s',rir:'1–2'},
{id:'one-arm-pulldown',cat:'back',sub:'lats',en:'One-Arm Cable Pulldown',ar:'سحب كيبل يد واحدة للاتس',eq:'cable',sets:3,reps:'10–12',rest:'75s',rir:'1–2'},
{id:'straight-arm-pulldown',cat:'back',sub:'lats',en:'Straight-Arm Pulldown',ar:'سحب كيبل بذراع مستقيمة',eq:'cable',sets:3,reps:'10–15',rest:'60–75s',rir:'1–2'},
{id:'pull-up',cat:'back',sub:'lats',en:'Pull-Up',ar:'عقلة',eq:'bodyweight',sets:3,reps:'6–12',rest:'120s',rir:'1–2'},
{id:'barbell-row',cat:'back',sub:'upper',en:'Barbell Row',ar:'تجديف بار',eq:'barbell',sets:4,reps:'6–10',rest:'120s',rir:'1–2'},
{id:'seated-row',cat:'back',sub:'upper',en:'Seated Cable Row',ar:'تجديف كيبل جالس',eq:'cable',sets:3,reps:'8–12',rest:'90s',rir:'1–2'},
{id:'one-arm-db-row',cat:'back',sub:'upper',en:'One-Arm Dumbbell Row',ar:'تجديف دمبل يد واحدة',eq:'dumbbell',sets:3,reps:'8–12/side',rest:'75s',rir:'1–2'},
{id:'chest-supported-row',cat:'back',sub:'upper',en:'Chest-Supported Row',ar:'تجديف مدعوم للصدر',eq:'machine',sets:3,reps:'8–12',rest:'90s',rir:'1–2'},
{id:'tbar-row',cat:'back',sub:'upper',en:'T-Bar Row',ar:'تجديف تي بار',eq:'machine',sets:3,reps:'8–12',rest:'90s',rir:'1–2'},
{id:'back-extension',cat:'back',sub:'lower',en:'Back Extension',ar:'تمديد أسفل الظهر',eq:'bodyweight',sets:3,reps:'10–15',rest:'60–90s',rir:'2'},
{id:'good-morning',cat:'back',sub:'lower',en:'Good Morning',ar:'جود مورنينغ',eq:'barbell',sets:3,reps:'8–12',rest:'90s',rir:'2'},

{id:'close-grip-lat-pulldown',cat:'back',sub:'lats',en:'Close-Grip Lat Pulldown',ar:'سحب لاتس قبضة ضيقة',eq:'cable',sets:3,reps:'10–12',rest:'75s',rir:'1–2'},
{id:'kneeling-straight-arm-pulldown',cat:'back',sub:'lats',en:'Kneeling Straight-Arm Pulldown',ar:'سحب مستقيم من الركوع',eq:'cable',sets:3,reps:'10–12',rest:'75s',rir:'1–2'},
{id:'deadlift',cat:'back',sub:'lower',en:'Barbell Deadlift',ar:'ديدلفت بالبار',eq:'barbell',sets:3,reps:'10–12',rest:'75s',rir:'1–2'},
{id:'wide-straight-arm-pulldown',cat:'back',sub:'lats',en:'Wide-Grip Straight-Arm Pulldown',ar:'سحب مستقيم قبضة واسعة',eq:'cable',sets:3,reps:'10–12',rest:'75s',rir:'1–2'},
{id:'plate-loaded-lat-pulldown',cat:'back',sub:'lats',en:'Plate-Loaded Lat Pulldown',ar:'سحب لاتس جهاز أوزان',eq:'machine',sets:3,reps:'10–12',rest:'75s',rir:'1–2'},
{id:'supported-one-arm-cable-row',cat:'back',sub:'upper',en:'Supported Single-Arm Cable Row',ar:'تجديف كيبل يد واحدة مدعوم',eq:'cable',sets:3,reps:'10–12',rest:'75s',rir:'1–2'},
{id:'chest-supported-db-row',cat:'back',sub:'upper',en:'Chest-Supported Dumbbell Row',ar:'تجديف دمبل مدعوم للصدر',eq:'dumbbell',sets:3,reps:'10–12',rest:'75s',rir:'1–2'},
{id:'wide-seated-row',cat:'back',sub:'upper',en:'Wide-Grip Seated Cable Row',ar:'تجديف كيبل جالس قبضة واسعة',eq:'cable',sets:3,reps:'10–12',rest:'75s',rir:'1–2'},
{id:'back-db-pullover',cat:'back',sub:'lats',en:'Dumbbell Pullover (Back Focus)',ar:'بول أوفر دمبل للظهر',eq:'dumbbell',sets:3,reps:'10–12',rest:'75s',rir:'1–2'},
{id:'close-seated-row',cat:'back',sub:'upper',en:'Close-Grip Seated Cable Row',ar:'تجديف كيبل جالس قبضة ضيقة',eq:'cable',sets:3,reps:'10–12',rest:'75s',rir:'1–2'},
{id:'one-arm-seated-row',cat:'back',sub:'upper',en:'Single-Arm Seated Cable Row',ar:'تجديف كيبل جالس يد واحدة',eq:'cable',sets:3,reps:'10–12',rest:'75s',rir:'1–2'},
{id:'smith-row',cat:'back',sub:'upper',en:'Smith Machine Bent-Over Row',ar:'تجديف بار سميث منحني',eq:'machine',sets:3,reps:'10–12',rest:'75s',rir:'1–2'},

{id:'rope-straight-arm-pulldown',cat:'back',sub:'lats',en:'Rope Straight-Arm Pulldown',ar:'سحب كيبل بالحبل بذراعين شبه مستقيمتين',eq:'cable',sets:3,reps:'10–15',rest:'60–75s',rir:'1–2'},

{id:'db-shoulder-press',cat:'shoulders',sub:'front',en:'Dumbbell Shoulder Press',ar:'ضغط كتف دمبل',eq:'dumbbell',sets:3,reps:'8–12',rest:'90s',rir:'1–2'},
{id:'bb-overhead-press',cat:'shoulders',sub:'front',en:'Barbell Overhead Press',ar:'ضغط كتف بار',eq:'barbell',sets:3,reps:'6–10',rest:'120s',rir:'1–2'},
{id:'machine-shoulder-press',cat:'shoulders',sub:'front',en:'Machine Shoulder Press',ar:'ضغط كتف جهاز',eq:'machine',sets:3,reps:'8–12',rest:'90s',rir:'1–2'},
{id:'front-raise',cat:'shoulders',sub:'front',en:'Dumbbell Front Raise',ar:'رفرفة أمامية دمبل',eq:'dumbbell',sets:3,reps:'10–15',rest:'60s',rir:'1–2'},
{id:'lateral-raise',cat:'shoulders',sub:'side',en:'Dumbbell Lateral Raise',ar:'رفرفة جانبية دمبل',eq:'dumbbell',sets:4,reps:'10–15',rest:'60s',rir:'1–2'},
{id:'cable-lateral',cat:'shoulders',sub:'side',en:'Cable Lateral Raise',ar:'رفرفة جانبية كيبل',eq:'cable',sets:3,reps:'12–15',rest:'60s',rir:'1–2'},
{id:'machine-lateral',cat:'shoulders',sub:'side',en:'Machine Lateral Raise',ar:'رفرفة جانبية جهاز',eq:'machine',sets:3,reps:'10–15',rest:'60s',rir:'1–2'},
{id:'reverse-pec-deck',cat:'shoulders',sub:'rear',en:'Reverse Pec Deck',ar:'رفرفة خلفية جهاز',eq:'machine',sets:4,reps:'10–15',rest:'60–75s',rir:'1–2'},
{id:'rear-delt-cable',cat:'shoulders',sub:'rear',en:'Rear Delt Cable Fly',ar:'رفرفة كتف خلفي كيبل',eq:'cable',sets:3,reps:'12–15',rest:'60s',rir:'1–2'},
{id:'rear-delt-db',cat:'shoulders',sub:'rear',en:'Bent-Over Rear Delt Raise',ar:'رفرفة خلفية دمبل منحني',eq:'dumbbell',sets:3,reps:'12–15',rest:'60s',rir:'1–2'},
{id:'face-pull',cat:'shoulders',sub:'rear',en:'Face Pull',ar:'فيس بول',eq:'cable',sets:3,reps:'12–15',rest:'60s',rir:'1–2'},

{id:'ez-curl',cat:'arms',sub:'biceps-short',en:'EZ-Bar Curl',ar:'بايسبس بار EZ',eq:'barbell',sets:3,reps:'8–12',rest:'75s',rir:'1–2'},
{id:'preacher-curl',cat:'arms',sub:'biceps-short',en:'Preacher Curl',ar:'بايسبس بريتشر',eq:'machine',sets:3,reps:'8–12',rest:'75s',rir:'1–2'},
{id:'concentration-curl',cat:'arms',sub:'biceps-short',en:'Concentration Curl',ar:'بايسبس تركيز',eq:'dumbbell',sets:3,reps:'10–15',rest:'60s',rir:'1–2'},
{id:'incline-curl',cat:'arms',sub:'biceps-long',en:'Incline Dumbbell Curl',ar:'بايسبس دمبل مائل',eq:'dumbbell',sets:3,reps:'8–12',rest:'75s',rir:'1–2'},
{id:'bayesian-curl',cat:'arms',sub:'biceps-long',en:'Bayesian Cable Curl',ar:'بايسبس بايزيان كيبل',eq:'cable',sets:3,reps:'10–15',rest:'60s',rir:'1–2'},
{id:'hammer-curl',cat:'arms',sub:'brachialis',en:'Hammer Curl',ar:'هامر كيرل',eq:'dumbbell',sets:3,reps:'10–12',rest:'60–75s',rir:'1–2'},
{id:'rope-hammer-curl',cat:'arms',sub:'brachialis',en:'Rope Hammer Curl',ar:'هامر كيرل حبل',eq:'cable',sets:3,reps:'10–15',rest:'60s',rir:'1–2'},
{id:'rope-pushdown',cat:'arms',sub:'triceps-lateral',en:'Rope Pushdown',ar:'ترايسبس حبل للأسفل',eq:'cable',sets:3,reps:'10–15',rest:'60–75s',rir:'1–2'},
{id:'straightbar-pushdown',cat:'arms',sub:'triceps-lateral',en:'Straight-Bar Pushdown',ar:'ترايسبس بار مستقيم للأسفل',eq:'cable',sets:3,reps:'10–15',rest:'60s',rir:'1–2'},
{id:'overhead-triceps',cat:'arms',sub:'triceps-long',en:'Overhead Cable Extension',ar:'تمديد ترايسبس فوق الرأس',eq:'cable',sets:3,reps:'10–15',rest:'60–75s',rir:'1–2'},
{id:'db-overhead-triceps',cat:'arms',sub:'triceps-long',en:'Dumbbell Overhead Extension',ar:'تمديد ترايسبس دمبل فوق الرأس',eq:'dumbbell',sets:3,reps:'10–15',rest:'75s',rir:'1–2'},
{id:'close-grip-press',cat:'arms',sub:'triceps',en:'Close-Grip Bench Press',ar:'بنش قبضة ضيقة',eq:'barbell',sets:3,reps:'6–10',rest:'120s',rir:'1–2'},

{id:'back-squat',cat:'legs',sub:'quads',en:'Back Squat',ar:'سكوات خلفي',eq:'barbell',sets:4,reps:'6–10',rest:'120–180s',rir:'1–2'},
{id:'front-squat',cat:'legs',sub:'quads',en:'Front Squat',ar:'سكوات أمامي',eq:'barbell',sets:3,reps:'6–10',rest:'120s',rir:'1–2'},
{id:'hack-squat',cat:'legs',sub:'quads',en:'Hack Squat',ar:'هاك سكوات',eq:'machine',sets:4,reps:'8–12',rest:'120s',rir:'1–2'},
{id:'leg-press',cat:'legs',sub:'quads',en:'Leg Press',ar:'ضغط الأرجل',eq:'machine',sets:4,reps:'8–12',rest:'120s',rir:'1–2'},
{id:'leg-extension',cat:'legs',sub:'quads',en:'Leg Extension',ar:'تمديد الأرجل',eq:'machine',sets:3,reps:'10–15',rest:'60–75s',rir:'1–2'},
{id:'bulgarian-split-squat',cat:'legs',sub:'quads',en:'Bulgarian Split Squat',ar:'بلغاريان سبليت سكوات',eq:'dumbbell',sets:3,reps:'8–12/side',rest:'90s',rir:'1–2'},
{id:'rdl',cat:'legs',sub:'hamstrings',en:'Romanian Deadlift',ar:'ديدلفت روماني',eq:'barbell',sets:4,reps:'6–10',rest:'120s',rir:'1–2'},
{id:'db-rdl',cat:'legs',sub:'hamstrings',en:'Dumbbell Romanian Deadlift',ar:'ديدلفت روماني دمبل',eq:'dumbbell',sets:3,reps:'8–12',rest:'90s',rir:'1–2'},
{id:'seated-leg-curl',cat:'legs',sub:'hamstrings',en:'Seated Leg Curl',ar:'ليج كيرل جالس',eq:'machine',sets:3,reps:'10–15',rest:'75s',rir:'1–2'},
{id:'lying-leg-curl',cat:'legs',sub:'hamstrings',en:'Lying Leg Curl',ar:'ليج كيرل مستلقي',eq:'machine',sets:3,reps:'10–15',rest:'75s',rir:'1–2'},
{id:'hip-thrust',cat:'legs',sub:'glutes',en:'Hip Thrust',ar:'هيب ثرست',eq:'barbell',sets:4,reps:'8–12',rest:'90–120s',rir:'1–2'},
{id:'glute-kickback',cat:'legs',sub:'glutes',en:'Cable Glute Kickback',ar:'ركلة خلفية للمؤخرة كيبل',eq:'cable',sets:3,reps:'12–15/side',rest:'60s',rir:'1–2'},
{id:'hip-abduction',cat:'legs',sub:'glutes',en:'Hip Abduction Machine',ar:'جهاز فتح الورك',eq:'machine',sets:3,reps:'12–20',rest:'60s',rir:'1–2'},
{id:'hip-adduction',cat:'legs',sub:'adductors',en:'Hip Adduction Machine',ar:'جهاز ضم الورك',eq:'machine',sets:3,reps:'12–20',rest:'60s',rir:'1–2'},
{id:'standing-calf',cat:'legs',sub:'calves',en:'Standing Calf Raise',ar:'رفع سمانة واقف',eq:'machine',sets:4,reps:'10–15',rest:'60s',rir:'1–2'},
{id:'seated-calf',cat:'legs',sub:'calves',en:'Seated Calf Raise',ar:'رفع سمانة جالس',eq:'machine',sets:4,reps:'10–15',rest:'60s',rir:'1–2'},

{id:'cable-crunch',cat:'core',sub:'abs',en:'Cable Crunch',ar:'كرنش كيبل',eq:'cable',sets:3,reps:'10–15',rest:'60s',rir:'1–2'},
{id:'machine-crunch',cat:'core',sub:'abs',en:'Ab Crunch Machine',ar:'كرنش بطن جهاز',eq:'machine',sets:3,reps:'10–15',rest:'60s',rir:'1–2'},
{id:'hanging-leg-raise',cat:'core',sub:'lower-abs',en:'Hanging Leg Raise',ar:'رفع الأرجل معلق',eq:'bodyweight',sets:3,reps:'8–15',rest:'60s',rir:'1–2'},
{id:'reverse-crunch',cat:'core',sub:'lower-abs',en:'Reverse Crunch',ar:'كرنش عكسي',eq:'bodyweight',sets:3,reps:'12–20',rest:'60s',rir:'1–2'},
{id:'pallof-press',cat:'core',sub:'obliques',en:'Pallof Press',ar:'بالوف برس',eq:'cable',sets:3,reps:'10–15/side',rest:'60s',rir:'2'},
{id:'cable-woodchop',cat:'core',sub:'obliques',en:'Cable Woodchop',ar:'وود تشوب كيبل',eq:'cable',sets:3,reps:'10–15/side',rest:'60s',rir:'2'},
{id:'plank',cat:'core',sub:'stability',en:'Plank',ar:'بلانك',eq:'bodyweight',sets:3,reps:'30–60s',rest:'60s',rir:'2'}
];
window.DEV_EXERCISE_CATEGORIES={chest:{en:'Chest',ar:'الصدر'},back:{en:'Back',ar:'الظهر'},shoulders:{en:'Shoulders',ar:'الأكتاف'},arms:{en:'Arms',ar:'الذراعين'},legs:{en:'Legs',ar:'الأرجل'},core:{en:'Abs & Core',ar:'البطن والكور'}};
