/* DEV GYM exercise library v1 — bilingual, equipment-aware. Visual assets use a single consistent illustrated male model: black T-shirt + black shorts. */
window.DEV_EXERCISES = [
{id:'incline-db-press',cat:'chest',sub:'upper',en:'Incline Dumbbell Press',ar:'ضغط دمبل مائل للأعلى',eq:'dumbbell',sets:4,reps:'8–10',rest:'90–120s',rir:'1–2'},
{id:'incline-bb-press',cat:'chest',sub:'upper',en:'Incline Barbell Press',ar:'ضغط بار مائل للأعلى',eq:'barbell',sets:4,reps:'6–10',rest:'120s',rir:'1–2'},
{id:'flat-db-press',cat:'chest',sub:'mid',en:'Dumbbell Bench Press',ar:'ضغط دمبل مستوي',eq:'dumbbell',sets:3,reps:'8–12',rest:'90s',rir:'1–2'},
{id:'chest-press-machine',cat:'chest',sub:'mid',en:'Chest Press Machine',ar:'ضغط صدر جهاز',eq:'machine',sets:3,reps:'8–12',rest:'90s',rir:'1–2'},
{id:'cable-fly',cat:'chest',sub:'mid',en:'Cable Fly',ar:'تفتيح كيبل',eq:'cable',sets:3,reps:'10–15',rest:'60–90s',rir:'1–2'},
{id:'high-to-low-fly',cat:'chest',sub:'lower',en:'High to Low Cable Fly',ar:'تفتيح كيبل من أعلى لأسفل',eq:'cable',sets:3,reps:'10–15',rest:'60–90s',rir:'1–2'},
{id:'lat-pulldown',cat:'back',sub:'lats',en:'Lat Pulldown',ar:'سحب أمامي للاتس',eq:'cable',sets:4,reps:'8–12',rest:'90s',rir:'1–2'},
{id:'one-arm-pulldown',cat:'back',sub:'lats',en:'One-Arm Cable Pulldown',ar:'سحب كيبل يد واحدة للاتس',eq:'cable',sets:3,reps:'10–12',rest:'75s',rir:'1–2'},
{id:'barbell-row',cat:'back',sub:'upper',en:'Barbell Row',ar:'تجديف بار',eq:'barbell',sets:4,reps:'6–10',rest:'120s',rir:'1–2'},
{id:'seated-row',cat:'back',sub:'upper',en:'Seated Cable Row',ar:'تجديف كيبل جالس',eq:'cable',sets:3,reps:'8–12',rest:'90s',rir:'1–2'},
{id:'chest-supported-row',cat:'back',sub:'upper',en:'Chest-Supported Row',ar:'تجديف مدعوم للصدر',eq:'machine',sets:3,reps:'8–12',rest:'90s',rir:'1–2'},
{id:'back-extension',cat:'back',sub:'lower',en:'Back Extension',ar:'تمديد أسفل الظهر',eq:'bodyweight',sets:3,reps:'10–15',rest:'60–90s',rir:'2'},
{id:'db-shoulder-press',cat:'shoulders',sub:'front',en:'Dumbbell Shoulder Press',ar:'ضغط كتف دمبل',eq:'dumbbell',sets:3,reps:'8–12',rest:'90s',rir:'1–2'},
{id:'lateral-raise',cat:'shoulders',sub:'side',en:'Dumbbell Lateral Raise',ar:'رفرفة جانبية دمبل',eq:'dumbbell',sets:4,reps:'10–15',rest:'60s',rir:'1–2'},
{id:'cable-lateral',cat:'shoulders',sub:'side',en:'Cable Lateral Raise',ar:'رفرفة جانبية كيبل',eq:'cable',sets:3,reps:'12–15',rest:'60s',rir:'1–2'},
{id:'reverse-pec-deck',cat:'shoulders',sub:'rear',en:'Reverse Pec Deck',ar:'رفرفة خلفية جهاز',eq:'machine',sets:4,reps:'10–15',rest:'60–75s',rir:'1–2'},
{id:'rear-delt-cable',cat:'shoulders',sub:'rear',en:'Rear Delt Cable Fly',ar:'رفرفة كتف خلفي كيبل',eq:'cable',sets:3,reps:'12–15',rest:'60s',rir:'1–2'},
{id:'ez-curl',cat:'arms',sub:'biceps-short',en:'EZ-Bar Curl',ar:'بايسبس بار EZ',eq:'barbell',sets:3,reps:'8–12',rest:'75s',rir:'1–2'},
{id:'incline-curl',cat:'arms',sub:'biceps-long',en:'Incline Dumbbell Curl',ar:'بايسبس دمبل مائل',eq:'dumbbell',sets:3,reps:'8–12',rest:'75s',rir:'1–2'},
{id:'hammer-curl',cat:'arms',sub:'brachialis',en:'Hammer Curl',ar:'هامر كيرل',eq:'dumbbell',sets:3,reps:'10–12',rest:'60–75s',rir:'1–2'},
{id:'rope-pushdown',cat:'arms',sub:'triceps-lateral',en:'Rope Pushdown',ar:'ترايسبس حبل للأسفل',eq:'cable',sets:3,reps:'10–15',rest:'60–75s',rir:'1–2'},
{id:'overhead-triceps',cat:'arms',sub:'triceps-long',en:'Overhead Cable Extension',ar:'تمديد ترايسبس فوق الرأس',eq:'cable',sets:3,reps:'10–15',rest:'60–75s',rir:'1–2'},
{id:'close-grip-press',cat:'arms',sub:'triceps',en:'Close-Grip Bench Press',ar:'بنش قبضة ضيقة',eq:'barbell',sets:3,reps:'6–10',rest:'120s',rir:'1–2'},
{id:'back-squat',cat:'legs',sub:'quads',en:'Back Squat',ar:'سكوات خلفي',eq:'barbell',sets:4,reps:'6–10',rest:'120–180s',rir:'1–2'},
{id:'leg-press',cat:'legs',sub:'quads',en:'Leg Press',ar:'ضغط الأرجل',eq:'machine',sets:4,reps:'8–12',rest:'120s',rir:'1–2'},
{id:'leg-extension',cat:'legs',sub:'quads',en:'Leg Extension',ar:'تمديد الأرجل',eq:'machine',sets:3,reps:'10–15',rest:'60–75s',rir:'1–2'},
{id:'rdl',cat:'legs',sub:'hamstrings',en:'Romanian Deadlift',ar:'ديدلفت روماني',eq:'barbell',sets:4,reps:'6–10',rest:'120s',rir:'1–2'},
{id:'seated-leg-curl',cat:'legs',sub:'hamstrings',en:'Seated Leg Curl',ar:'ليج كيرل جالس',eq:'machine',sets:3,reps:'10–15',rest:'75s',rir:'1–2'},
{id:'hip-thrust',cat:'legs',sub:'glutes',en:'Hip Thrust',ar:'هيب ثرست',eq:'barbell',sets:4,reps:'8–12',rest:'90–120s',rir:'1–2'},
{id:'standing-calf',cat:'legs',sub:'calves',en:'Standing Calf Raise',ar:'رفع سمانة واقف',eq:'machine',sets:4,reps:'10–15',rest:'60s',rir:'1–2'},
{id:'cable-crunch',cat:'core',sub:'abs',en:'Cable Crunch',ar:'كرنش كيبل',eq:'cable',sets:3,reps:'10–15',rest:'60s',rir:'1–2'},
{id:'hanging-leg-raise',cat:'core',sub:'lower-abs',en:'Hanging Leg Raise',ar:'رفع الأرجل معلق',eq:'bodyweight',sets:3,reps:'8–15',rest:'60s',rir:'1–2'},
{id:'pallof-press',cat:'core',sub:'obliques',en:'Pallof Press',ar:'بالوف برس',eq:'cable',sets:3,reps:'10–15/side',rest:'60s',rir:'2'}
];
window.DEV_EXERCISE_CATEGORIES={chest:{en:'Chest',ar:'الصدر'},back:{en:'Back',ar:'الظهر'},shoulders:{en:'Shoulders',ar:'الأكتاف'},arms:{en:'Arms',ar:'الذراعين'},legs:{en:'Legs',ar:'الأرجل'},core:{en:'Abs & Core',ar:'البطن والكور'}};
